# Generated by Django 4.0.5 on 2022-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug_alter_tag_slug_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=161, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=61, unique=True, verbose_name='Slug'),
        ),
    ]
